[#112] Authorization
odahu/odahu-infra pull request #2
Opened 2020-01-22 19:57 UTC by vlad-tokarev

* Add helm chart for openpolicyagent deployment
* Write MVP version of authorization policies (policy.rego file)

2020-01-23 06:46 UTC, mcdoker18 requested changes

2020-01-23 06:46 UTC, mcdoker18 commented on helms/odahu-flow-authorization/files/openpolicyagent/policy.rego
> +package odahu
IMHO, this is the wrong place for a policy file.
I thought that we would keep policies in the odahu-automation or legion-profiles repository.
I don't want to change the helm chart whenever my policies are changed.

2020-01-23 06:46 UTC, mcdoker18 commented on helms/odahu-flow-authorization/values.yaml
> +  tag: latest-istio
Pin a some version

2020-01-23 06:46 UTC, mcdoker18 commented on helms/odahu-flow-authorization/Chart.yaml
> +name: odahu-flow-authorization
Why not `odahu-flow-opa`?

2020-01-23 06:46 UTC, mcdoker18 commented on helms/odahu-flow-authorization/values.yaml
> +
A user should override the policies.

2020-01-23 06:46 UTC, mcdoker18 commented on helms/odahu-flow-authorization/files/openpolicyagent/config.yaml
> +decision_logs:
Do you use this file anywhere?

2020-02-03 16:41 UTC, mcdoker18 requested changes

2020-02-03 16:41 UTC, mcdoker18 commented on helms/odahu-flow-opa/files/openpolicyagent/policy.rego
> +
Did you not forget to delete this file?

2020-02-03 21:18 UTC, mcdoker18 approved these changes

2020-02-04 08:55 UTC, maxkochubey approved these changes

2020-02-05 11:05 UTC, merged