[#9] collect opa logs
odahu/odahu-infra pull request #25
Opened 2020-10-14 09:32 UTC by karbyshevds

closes #9

- Update openpolicyagent 0.16.1-istio-4 -> 0.23.2-istio-2
- Filter `x-jwt` header and cookie from logs
- Do not forward JWT token from istio

2020-10-16 11:02 UTC, vlad-tokarev requested changes

2020-10-16 11:02 UTC, vlad-tokarev commented on helms/odahu-flow-opa/policies/masker.rego
> +mask[{"op": "upsert", "path": "/input/attributes/request/http/headers/cookie", "value": x}] {
also /input/attributes/request/http/headers/authorization

2020-10-19 10:33 UTC, vlad-tokarev approved these changes

2020-10-19 13:28 UTC, easokol approved these changes

2020-10-19 23:09 UTC, merged